name: .NET Publish and Release

on:
  push:
    tags:
      - 'v*' # 当匹配 'v*.*.*' 格式的标签被推送时触发
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true
        type: string
        default: '1.0.0'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest # 使用 Windows 环境

    permissions:
      contents: write # 需要写入权限来创建 Release 和上传构建产物

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          cache: true

      - name: Install frontend dependencies
        working-directory: ./web-ui
        run: pnpm install

      - name: Build frontend
        working-directory: ./web-ui
        run: pnpm build

      - name: Set version
        id: set_version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            echo "VERSION=${{ github.event.inputs.version }}" >> $env:GITHUB_OUTPUT
          } else {
            $tag = "${{ github.ref }}" -replace "refs/tags/v", ""
            echo "VERSION=$tag" >> $env:GITHUB_OUTPUT
          }

      - name: Build and publish for win-x64
        run: dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -p:SelfContained=false -p:EnableCompressionInSingleFile=false -p:Version=${{ steps.set_version.outputs.VERSION }} -p:AssemblyVersion=${{ steps.set_version.outputs.VERSION }} -p:FileVersion=${{ steps.set_version.outputs.VERSION }} --output ./publish-x64

      - name: Rename win-x64 executable
        run: ren publish-x64\MyLanServer.exe MyLanServer-x64.exe

      - name: Archive win-x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyLanServer-win-x64-files
          path: ./publish-x64

      - name: Build and publish for win-x86
        run: dotnet publish -c Release -r win-x86 --self-contained false -p:PublishSingleFile=true -p:SelfContained=false -p:EnableCompressionInSingleFile=false -p:Version=${{ steps.set_version.outputs.VERSION }} -p:AssemblyVersion=${{ steps.set_version.outputs.VERSION }} -p:FileVersion=${{ steps.set_version.outputs.VERSION }} --output ./publish-x86

      - name: Rename win-x86 executable
        run: ren publish-x86\MyLanServer.exe MyLanServer-x86.exe

      - name: Archive win-x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyLanServer-win-x86-files
          path: ./publish-x86

      - name: Create Release and Upload Assets
        if: startsWith(github.ref, 'refs/tags/') # 仅当事件是标签推送时执行
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./publish-*/*.exe
